import { useEffect, useMemo, useRef, useState } from 'react';
import { Camera, Gauge, Pause, Play, RotateCcw, Upload } from 'lucide-react';
import { ThreeMmdRuntime, type MmdRuntimeState } from '@our-stage/mmd-runtime';
import { evaluateTimeline } from '@our-stage/timeline-engine';
import { useProjectStore } from '../store/projectStore';
const initialState:MmdRuntimeState={modelLoaded:false,motionLoaded:false,playing:false,currentTime:0,duration:0,diagnostics:null,error:null};
const lerp=(a:number,b:number,p:number)=>a+(b-a)*p;
export function MmdViewport(){const canvasRef=useRef<HTMLCanvasElement>(null),runtimeRef=useRef<ThreeMmdRuntime|null>(null),loadedModelRef=useRef<string|null>(null),loadedMotionRef=useRef<string|null>(null);const[runtimeState,setRuntimeState]=useState(initialState),[busy,setBusy]=useState(false);const project=useProjectStore((s)=>s.project),selectedActorId=useProjectStore((s)=>s.selectedActorId),selectedAssetId=useProjectStore((s)=>s.selectedAssetId),currentTime=useProjectStore((s)=>s.currentTime),timelinePlaying=useProjectStore((s)=>s.timelinePlaying),importModel=useProjectStore((s)=>s.importModel),importMotion=useProjectStore((s)=>s.importMotion),setTimelinePlaying=useProjectStore((s)=>s.setTimelinePlaying),setCurrentTime=useProjectStore((s)=>s.setCurrentTime);const actor=useMemo(()=>project.actors.find((i)=>i.actorId===selectedActorId)??project.actors[0],[project.actors,selectedActorId]);const modelAsset=project.assets.find((a)=>a.assetId===actor?.modelAssetId);const evaluation=useMemo(()=>evaluateTimeline(project,currentTime),[project,currentTime]);const activeMotion=evaluation.active.find((i)=>i.track.type==='motion'&&i.track.actorId===actor?.actorId);const selectedMotion=project.assets.find((a)=>a.assetId===selectedAssetId&&a.type==='vmd-motion');const hasTimelineMotion=project.tracks.some((t)=>t.type==='motion'&&t.clips.length>0);const motionAsset=activeMotion?.clip.type==='motion'?project.assets.find((a)=>a.assetId===activeMotion.clip.motionAssetId):!hasTimelineMotion?selectedMotion??project.assets.find((a)=>a.type==='vmd-motion'):undefined;const motionLocalTime=activeMotion?.localTimeSeconds??currentTime;
useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const runtime=new ThreeMmdRuntime(canvas);runtimeRef.current=runtime;const unsubscribe=runtime.subscribe(setRuntimeState);return()=>{unsubscribe();runtime.dispose();runtimeRef.current=null;};},[]);
useEffect(()=>{const runtime=runtimeRef.current;if(!runtime||!modelAsset?.runtimeUrl||loadedModelRef.current===modelAsset.assetId)return;loadedModelRef.current=modelAsset.assetId;loadedMotionRef.current=null;setBusy(true);void runtime.loadModel(modelAsset.runtimeUrl,modelAsset.title).catch(()=>{loadedModelRef.current=null;}).finally(()=>setBusy(false));},[modelAsset?.assetId,modelAsset?.runtimeUrl,modelAsset?.title]);
useEffect(()=>{const runtime=runtimeRef.current;if(!runtime||!runtimeState.modelLoaded||!motionAsset?.runtimeUrl)return;if(loadedMotionRef.current===motionAsset.assetId){runtime.seek(motionLocalTime);return;}loadedMotionRef.current=motionAsset.assetId;setBusy(true);void runtime.loadMotion(motionAsset.runtimeUrl).then(()=>runtime.seek(motionLocalTime)).catch(()=>{loadedMotionRef.current=null;}).finally(()=>setBusy(false));},[motionAsset?.assetId,motionAsset?.runtimeUrl,motionLocalTime,runtimeState.modelLoaded]);
useEffect(()=>{const runtime=runtimeRef.current;if(!runtime||!actor)return;const transformEntry=evaluation.active.find((i)=>i.track.type==='transform'&&i.track.actorId===actor.actorId);if(transformEntry?.clip.type==='transform'){const{from,to}=transformEntry.clip,p=transformEntry.progress;runtime.setActorTransform({position:from.position.map((v,i)=>lerp(v,to.position[i]??v,p)) as [number,number,number],rotationEuler:from.rotationEuler.map((v,i)=>lerp(v,to.rotationEuler[i]??v,p)) as [number,number,number],scale:from.scale.map((v,i)=>lerp(v,to.scale[i]??v,p)) as [number,number,number]});}else runtime.setActorTransform(actor.initialTransform);runtime.resetMorphs();for(const item of evaluation.active)if(item.track.type==='expression'&&item.clip.type==='expression')runtime.setMorph(item.clip.morphName,item.clip.weight);const cameraEntry=evaluation.active.find((i)=>i.clip.type==='camera');if(cameraEntry?.clip.type==='camera')runtime.applyCameraPreset(cameraEntry.clip.presetId);},[actor,evaluation]);
return <section className="viewport-panel"><div className="viewport-toolbar"><button type="button" onClick={()=>void importModel()} disabled={busy}><Upload size={16}/> PMX</button><button type="button" onClick={()=>void importMotion()} disabled={busy||!runtimeState.modelLoaded}><Upload size={16}/> VMD</button><span className="toolbar-divider"/><button type="button" onClick={()=>setTimelinePlaying(!timelinePlaying)} disabled={!runtimeState.motionLoaded}>{timelinePlaying?<Pause size={16}/>:<Play size={16}/>}</button><button type="button" onClick={()=>{setTimelinePlaying(false);setCurrentTime(0);}} disabled={!runtimeState.modelLoaded}><RotateCcw size={16}/></button><span className="time-readout">{currentTime.toFixed(2)} / {project.output.durationSeconds.toFixed(2)}s</span><label className="quality-select"><Gauge size={15}/><select defaultValue="preview" onChange={(e)=>runtimeRef.current?.setQuality(e.target.value as 'draft'|'preview'|'final')}><option value="draft">Draft</option><option value="preview">Preview</option><option value="final">Final</option></select></label></div><div className="viewport-canvas-wrap"><canvas ref={canvasRef}/>{!runtimeState.modelLoaded&&<div className="viewport-empty"><Camera size={38}/><strong>Import a PMX model</strong><span>Desktop mode resolves the model and relative texture files locally.</span></div>}{runtimeState.error&&<div className="viewport-error">{runtimeState.error}</div>}</div><div className="viewport-status"><span>{runtimeState.modelLoaded?'Model ready':'No model'}</span><span>{runtimeState.motionLoaded?'Motion ready':'No motion'}</span><span>{activeMotion?`Timeline: ${activeMotion.clip.label??'motion'}`:'Timeline idle'}</span></div>{runtimeState.diagnostics&&<div className="diagnostic-strip"><strong>{runtimeState.diagnostics.name}</strong><span>{runtimeState.diagnostics.bones} bones</span><span>{runtimeState.diagnostics.morphTargets} morphs</span><span>{runtimeState.diagnostics.materials} materials</span><span title={runtimeState.diagnostics.renderer}>{runtimeState.diagnostics.renderer}</span></div>}</section>}
