import { AmbientLight, Clock, Color, DirectionalLight, GridHelper, Object3D, PerspectiveCamera, SkinnedMesh, Scene, Vector3, WebGLRenderer } from 'three';
import { MMDAnimationHelper } from 'three/addons/animation/MMDAnimationHelper.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { OutlineEffect } from 'three/addons/effects/OutlineEffect.js';
import { MMDLoader } from 'three/addons/loaders/MMDLoader.js';
export type RuntimeQuality='draft'|'preview'|'final';
export interface MmdModelDiagnostics{name:string;bones:number;morphTargets:number;materials:number;meshes:number;physicsAvailable:boolean;renderer:string}
export interface MmdRuntimeState{modelLoaded:boolean;motionLoaded:boolean;playing:boolean;currentTime:number;duration:number;diagnostics:MmdModelDiagnostics|null;error:string|null}
export type RuntimeListener=(state:MmdRuntimeState)=>void;
interface HelperObjectState{mixer?:{setTime:(time:number)=>void;update:(delta:number)=>void};physics?:{reset:()=>void}}
export class ThreeMmdRuntime{readonly scene=new Scene();readonly camera=new PerspectiveCamera(35,1,.1,2000);readonly renderer:WebGLRenderer;private readonly effect:OutlineEffect;private readonly controls:OrbitControls;private readonly loader=new MMDLoader();private readonly helper=new MMDAnimationHelper({afterglow:0});private readonly clock=new Clock();private readonly listeners=new Set<RuntimeListener>();private model:SkinnedMesh|null=null;private frameHandle:number|null=null;private state:MmdRuntimeState={modelLoaded:false,motionLoaded:false,playing:false,currentTime:0,duration:0,diagnostics:null,error:null};
constructor(private readonly canvas:HTMLCanvasElement){this.renderer=new WebGLRenderer({canvas,antialias:true,alpha:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.effect=new OutlineEffect(this.renderer,{defaultThickness:.0025,defaultColor:[.08,.05,.12]});this.scene.background=new Color('#17131f');this.camera.position.set(0,12,34);this.controls=new OrbitControls(this.camera,this.canvas);this.controls.target.set(0,10,0);this.controls.enableDamping=true;const ambient=new AmbientLight('#fff',1.25),key=new DirectionalLight('#fff4fb',2.4);key.position.set(8,18,14);key.castShadow=true;key.shadow.mapSize.set(2048,2048);const fill=new DirectionalLight('#aa9cff',.8);fill.position.set(-10,9,-4);this.scene.add(ambient,key,fill,new GridHelper(40,40,'#554768','#30283b'));this.resize();this.animate=this.animate.bind(this);this.frameHandle=requestAnimationFrame(this.animate)}
subscribe(listener:RuntimeListener){this.listeners.add(listener);listener(this.state);return()=>this.listeners.delete(listener)}getState(){return this.state}
async loadModel(url:string,displayName='Imported PMX'){this.setState({error:null,playing:false});try{const mesh=await new Promise<SkinnedMesh>((resolve,reject)=>this.loader.load(url,resolve,undefined,reject));this.clearModel();mesh.castShadow=true;mesh.receiveShadow=true;mesh.traverse((object)=>{const candidate=object as Object3D&{castShadow?:boolean;receiveShadow?:boolean};candidate.castShadow=true;candidate.receiveShadow=true});this.model=mesh;this.scene.add(mesh);this.helper.add(mesh,{physics:false});this.frameModel(mesh);this.setState({modelLoaded:true,motionLoaded:false,currentTime:0,duration:0,diagnostics:this.inspectModel(mesh,displayName)})}catch(error){this.setState({error:error instanceof Error?error.message:String(error)});throw error}}
async loadMotion(url:string){if(!this.model)throw new Error('Load a PMX model before loading a VMD motion.');try{const animation=await new Promise<import('three').AnimationClip>((resolve,reject)=>this.loader.loadAnimation(url,this.model as SkinnedMesh,resolve,undefined,reject));this.helper.remove(this.model);this.helper.add(this.model,{animation,physics:false});this.setState({motionLoaded:true,duration:animation.duration,currentTime:0,error:null});this.seek(0)}catch(error){this.setState({error:error instanceof Error?error.message:String(error)});throw error}}
play(){if(!this.state.motionLoaded)return;this.clock.start();this.setState({playing:true})}pause(){this.clock.stop();this.setState({playing:false})}
seek(seconds:number){const duration=this.state.duration||Number.POSITIVE_INFINITY,time=Math.max(0,Math.min(seconds,duration)),objectState=this.model?this.getHelperObject(this.model):undefined;objectState?.mixer?.setTime(time);this.helper.update(0);this.setState({currentTime:time});this.render()}
reset(){this.pause();this.getHelperObject(this.model)?.physics?.reset();this.seek(0)}
setMorph(name:string,weight:number){if(!this.model)return;const index=(this.model.morphTargetDictionary??{})[name];if(index===undefined||!this.model.morphTargetInfluences)return;this.model.morphTargetInfluences[index]=Math.min(1,Math.max(0,weight));this.render()}
resetMorphs(){this.model?.morphTargetInfluences?.fill(0)}
setActorTransform(transform:{position:[number,number,number];rotationEuler:[number,number,number];scale:[number,number,number]}){if(!this.model)return;this.model.position.set(...transform.position);this.model.rotation.set(...transform.rotationEuler);this.model.scale.set(...transform.scale);this.model.updateMatrixWorld(true)}
applyCameraPreset(presetId:string){const presets:Record<string,{position:[number,number,number];target:[number,number,number];fov:number}>={wide:{position:[0,12,44],target:[0,9,0],fov:40},'full-body':{position:[0,11,31],target:[0,9,0],fov:35},medium:{position:[0,13,23],target:[0,12,0],fov:32},'close-up':{position:[0,15,14],target:[0,15,0],fov:28}};const preset=presets[presetId]??presets.medium;if(!preset)return;this.camera.position.set(...preset.position);this.camera.fov=preset.fov;this.camera.updateProjectionMatrix();this.controls.target.set(...preset.target);this.controls.update()}
setQuality(quality:RuntimeQuality){const ratio=quality==='draft'?.75:quality==='preview'?1:Math.min(window.devicePixelRatio,2);this.renderer.setPixelRatio(ratio);this.resize()}
resize(){const width=Math.max(1,this.canvas.clientWidth),height=Math.max(1,this.canvas.clientHeight);if(this.canvas.width!==width||this.canvas.height!==height){this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.updateProjectionMatrix()}}
captureDataUrl(type:'image/png'|'image/jpeg'='image/png'){this.render();return this.canvas.toDataURL(type)}dispose(){if(this.frameHandle!==null)cancelAnimationFrame(this.frameHandle);this.clearModel();this.controls.dispose();this.renderer.dispose();this.listeners.clear()}
private animate(){this.frameHandle=requestAnimationFrame(this.animate);this.resize();if(this.state.playing){const delta=Math.min(this.clock.getDelta(),.1),next=this.state.currentTime+delta;if(this.state.duration>0&&next>=this.state.duration)this.seek(0);else{this.helper.update(delta);this.setState({currentTime:next})}}this.controls.update();this.render()}
private render(){this.effect.render(this.scene,this.camera)}private clearModel(){if(!this.model)return;this.helper.remove(this.model);this.scene.remove(this.model);this.model.traverse((object)=>{const resource=object as Object3D&{geometry?:{dispose:()=>void};material?:{dispose:()=>void}|Array<{dispose:()=>void}>};resource.geometry?.dispose();if(Array.isArray(resource.material))resource.material.forEach((material)=>material.dispose());else resource.material?.dispose()});this.model=null}
private frameModel(model:Object3D){const center=new Vector3();model.getWorldPosition(center);this.controls.target.set(center.x,center.y+10,center.z);this.camera.position.set(center.x,center.y+12,center.z+34);this.controls.update()}
private inspectModel(model:Object3D,name:string):MmdModelDiagnostics{let meshes=0,materials=0;model.traverse((object)=>{const mesh=object as Object3D&{isMesh?:boolean;material?:unknown|unknown[]};if(mesh.isMesh){meshes++;materials+=Array.isArray(mesh.material)?mesh.material.length:mesh.material?1:0}});const skinned=model as Object3D&{skeleton?:{bones:Object3D[]};morphTargetDictionary?:Record<string,number>},context=this.renderer.getContext(),debugInfo=context.getExtension('WEBGL_debug_renderer_info'),renderer=debugInfo?String(context.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL)):'WebGL renderer';return{name,bones:skinned.skeleton?.bones.length??0,morphTargets:Object.keys(skinned.morphTargetDictionary??{}).length,materials,meshes,physicsAvailable:false,renderer}}
private getHelperObject(model:SkinnedMesh|null){if(!model)return undefined;return (this.helper as unknown as{objects:WeakMap<SkinnedMesh,HelperObjectState>}).objects.get(model)}private setState(patch:Partial<MmdRuntimeState>){this.state={...this.state,...patch};for(const listener of this.listeners)listener(this.state)}}
export class DeterministicFrameClock{constructor(readonly fps:number){if(!Number.isFinite(fps)||fps<=0)throw new Error('FPS must be positive.')}timeAt(frameIndex:number){if(!Number.isInteger(frameIndex)||frameIndex<0)throw new Error('Frame index must be a non-negative integer.');return frameIndex/this.fps}frameCount(durationSeconds:number){return Math.ceil(durationSeconds*this.fps)}}
